# Generated by Django 5.0.4 on 2024-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('distance', models.FloatField()),
                ('pace', models.TimeField()),
            ],
        ),
    ]
